image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # добавления прав на запуск файла gradlew
  - chmod +x gradlew
  # загружает docker compose версию 1.26.0 и сохраняет исполняемый файл в каталоге /usr/local/bin/docker-compose, в результате чего данное программное обеспечение будет глобально доступно под именем docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  # задаёт разрешения, чтобы сделать команду docker-compose исполняемой
  - sudo chmod +x /usr/local/bin/docker-compose
  # проверка успешности установки
  - docker-compose --version
  # запускаем контейнеры с базой данных и симулятором платежей (-d означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - docker-compose up -d
  # ожидание поднятия контейнеров
  - sleep 30
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  # запускаем тест, флаг --info позволяет выводить больше информации, флаг -Dselenide.headless=true запуск selenide
  # в headless-режиме
  - ./gradlew test --info -Dselenide.headless=true
